name: Build iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App (Unsigned)
        run: flutter build ios --no-codesign --release

      - name: Package IPA
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Kloudera_Visiting_Card_Scanner.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kloudera_Visiting_Card_Scanner_iOS
          path: Kloudera_Visiting_Card_Scanner.ipa
